apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-leader
  labels:
    app: hermes-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes-leader
  template:
    metadata:
      labels:
        app: hermes-leader
    spec:
      containers:
        - name: tcp-kv-server
          image: r3musketeers/tcp-kv-server
          args: [
            "-l", "/tmp/throughput.log",
            "-b", "2048",
          ]
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 2000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          readinessProbe:
            tcpSocket:
              port: 8001
        - name: hermes-leader
          image: r3musketeers/hermes
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROTOCOL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PROTOCOL_PORT
              value: "10000"
          ports:
            - name: server
              containerPort: 8000
            - name: join
              containerPort: 9000
            - name: protocol
              containerPort: 10000
          resources:
            requests:
              cpu: 2000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          readinessProbe:
            tcpSocket:
              port: 8000
      nodeSelector:
        role: server
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "hermes-leader", "hermes-follower" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
---
apiVersion: v1
kind: Service
metadata:
  name: hermes-leader
spec:
  selector:
    app: hermes-leader
  type: NodePort
  ports:
    - name: server
      port: 8000
      targetPort: 8000
    - name: join
      port: 9000
      targetPort: 9000