apiVersion: batch/v1
kind: Job
metadata:
  name: tcp-kv-client
  # namespace: hermes
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        app: tcp-kv-client
    spec:
      containers:
      - name: tcp-kv-client
        image: r3musketeers/tcp-kv-client:latest
        args: [
          "-s", "tcp-kv-hashicorp-raft-leader:8000",
          "-d", "60s",
          "-p", "1024",
          "-k", "100000",
          "-r", "0",
          "-n", "42",
          "-t", "10ms",
          "-f", "100",
          "-b", "2048"
        ]
        resources:
          requests:
            cpu: 2000m
            memory: 2Gi
          limits:
              cpu: 4000m
              memory: 4Gi
      restartPolicy: Never
      nodeSelector:
        role: client
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "tcp-kv-client" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
  backoffLimit: 4