apiVersion: batch/v1
kind: Job
metadata:
  name: tcp-kv-client
spec:
  completions: $N_CLIENTS
  parallelism: $N_CLIENTS
  template:
    metadata:
      labels:
        app: tcp-kv-client
    spec:
      containers:
      - name: tcp-kv-client
        image: r3musketeers/tcp-kv-client:latest
        args: [
          "-s", "$SERVICE_NAME:8000",
          "-d", "60s",
          "-p", "128",
          "-k", "100000",
          "-r", "$READ_RATE",
          "-n", "$N_THREADS",
          "-t", "2ms",
          "-f", "20",
          "-b", "256"
        ]
        resources:
          requests:
            cpu: 2000m
            memory: 2Gi
          limits:
              cpu: 4000m
              memory: 4Gi
      restartPolicy: Never
      nodeSelector:
        role: client
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "tcp-kv-client" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
  backoffLimit: 4