apiVersion: batch/v1
kind: Job
metadata:
  name: tcp-kv-client
  namespace: hermes
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
      - name: tcp-kv-client
        image: r3musketeers/tcp-kv-client:latest
        # resources:
        #   requests:
        #     cpu: 4
        #   limits:
        #     cpu: 8
          # requests:
          #   memory: 100Mi
          # limits:
          #   memory: 200Mi
        # command: [ "/bin/tcp-kv-client", "-d", "2m", "-u", "http://10.244.2.5:11010/kv" ]
        args: [
          "-s", "172.17.0.6:8000",
          "-d", "10s",
          "-l", "/tmp/latency.log",
          "-p", "1024",
          "-k", "100000",
          "-r", "0",
          "-n", "16",
          "-t", "50ms",
          "-f", "10",
          "-b", "2048"
        ]
      restartPolicy: Never
      # nodeSelector:
      #   role: client
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "tcp-kv-client" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
  backoffLimit: 4