apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-kv-hashicorp-raft-follower
  labels:
    app: tcp-kv-hashicorp-raft-follower
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcp-kv-hashicorp-raft-follower
  template:
    metadata:
      labels:
        app: tcp-kv-hashicorp-raft-follower
    spec:
      containers:
        - name: tcp-kv-hashicorp-raft-follower
          image: r3musketeers/tcp-kv-hashicorp-raft
          args: [
            "-l", "/tmp/throughput.log",
            "-b", "2048",
            "-j", "tcp-kv-hashicorp-raft-leader:9000"
          ]
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROTOCOL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PROTOCOL_PORT
              value: "10000"
          ports:
            - name: server
              containerPort: 8000
            - name: join
              containerPort: 9000
            - name: protocol
              containerPort: 10000
          resources:
            requests:
              cpu: 2000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          readinessProbe:
            tcpSocket:
              port: 8000
      nodeSelector:
        role: server
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "tcp-kv-hashicorp-raft-leader", "tcp-kv-hashicorp-raft-follower" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone