apiVersion: batch/v1
kind: Job
metadata:
  name: tcp-kv-client
spec:
  backoffLimit: 5
  completions: $N_CLIENTS
  parallelism: $N_CLIENTS
  template:
    metadata:
      labels:
        app: tcp-kv-client
    spec:
      containers:
      - name: tcp-kv-client
        image: r3musketeers/tcp-kv-client:latest
        imagePullPolicy: Always
        args: [
          "-s", "$SERVICE_NAME:8000",
          "-d", "60s",
          "-p", "512",
          "-k", "100000",
          "-r", "$READ_RATE",
          "-n", "$N_THREADS",
          "-t", "2ms",
          "-f", "20",
          "-b", "1024"
        ]
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
      restartPolicy: Never
      nodeSelector:
        role: client
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "tcp-kv-client" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
