apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-kv-server
  labels:
    app: tcp-kv-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-kv-server
  template:
    metadata:
      labels:
        app: tcp-kv-server
    spec:
      containers:
        - name: tcp-kv-server
          image: r3musketeers/tcp-kv-server
          args: [
            "-l", "/tmp/throughput.log",
            "-b", "2048",
          ]
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 2000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi
          readinessProbe:
            tcpSocket:
              port: 8000
      nodeSelector:
        role: server
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "tcp-kv-server" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-kv-server
spec:
  selector:
    app: tcp-kv-server
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000