apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-followers
  labels:
    app: hermes-followers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hermes-followers
  template:
    metadata:
      labels:
        app: hermes-followers
    spec:
      containers:
        - name: http-log-server
          image: lptonussi/public:http-log-server
          imagePullPolicy: Always
          args: [
            '--address=localhost',
            '--port=8001'
          ]
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "100m"
              memory: "500Mi"
            limits:
              cpu: "100m"
              memory: "500Mi"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8001
        - name: hermes
          image: lptonussi/public:hermes
          imagePullPolicy: Always
          args: [
            "-j", "hermes-leader:9000"
          ]
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROTOCOL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PROTOCOL_PORT
              value: "10000"
          ports:
            - name: server
              containerPort: 8000
            - name: join
              containerPort: 9000
            - name: protocol
              containerPort: 10000
          resources:
            requests:
              cpu: "100m"
              memory: "500Mi"
            limits:
              cpu: "100m"
              memory: "500Mi"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
      nodeSelector:
        role: client
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "hermes-leader", "hermes-follower" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
