- hosts: master
  become: yes
  gather_facts: false
  tasks:
  
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:

    - name: restart service docker service
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker

    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt

- hosts: master
  become: yes
  tasks:

    - name: copy kube config
      become: yes
      become_user: "{{ ansible_user }}"
      fetch:
        src: $HOME/.kube/config
        dest: ~/.kube/config
        flat: yes