apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-followers
  labels:
    app: hermes-followers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hermes-followers
  template:
    metadata:
      labels:
        app: hermes-followers
    spec:
      containers:
        - name: kv
          image: lptonussi/public:tcp-kv-server
          imagePullPolicy: Always
          args: [
            "-l", "/tmp/throughput.log",
            "-b", "2048",
            "-v", "1024"
          ]
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          readinessProbe:
            tcpSocket:
              port: 8001
        - name: hermes
          image: r3musketeers/hermes
          imagePullPolicy: Always
          args: [
            "-j", "hermes-leader:9000"
          ]
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROTOCOL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PROTOCOL_PORT
              value: "10000"
          ports:
            - name: server
              containerPort: 8000
            - name: join
              containerPort: 9000
            - name: protocol
              containerPort: 10000
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          readinessProbe:
            tcpSocket:
              port: 8000
      nodeSelector:
        "kubernetes.io/role": "landowner"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "hermes-leader", "hermes-follower" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
