apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-leader
  labels:
    app: hermes-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes-leader
  template:
    metadata:
      labels:
        app: hermes-leader
    spec:
      containers:
        - name: kv
          image: lptonussi/public:tcp-kv-server
          imagePullPolicy: Always
          args: [
            "-l", "/tmp/throughput.log",
            "-b", "2048",
            "-v", "1024"
          ]
          volumeMounts:
            - name: hermes-volume-logs
              mountPath: /tmp/logs
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          # readinessProbe:
          #   tcpSocket:
          #     port: 8001
        - name: hermes
          image: lptonussi/public:hermes
          imagePullPolicy: Always
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROTOCOL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PROTOCOL_PORT
              value: "10000"
          ports:
            - name: server
              containerPort: 8000
            - name: join
              containerPort: 9000
            - name: protocol
              containerPort: 10000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 8000
      volumes:
        - name: hermes-volume-logs
          emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - landowner
---
apiVersion: v1
kind: Service
metadata:
  name: hermes-leader
spec:
  selector:
    app: hermes-leader
  type: NodePort
  ports:
    - name: server
      port: 8000
      targetPort: 8000
    - name: join
      port: 9000
      targetPort: 9000
