apiVersion: batch/v1
kind: Job
metadata:
  name: http-log-client
spec:
  backoffLimit: 5
  completions: $N_CLIENTS
  parallelism: $N_CLIENTS
  template:
    metadata:
      labels:
        app: http-log-client
    spec:
      containers:
      - name: http-log-client
        image: lptonussi/public:http-log-client
        imagePullPolicy: Always
        args: [
          '--address=$SERVICE_NAME',
          '--port=8001',
          '--duration=60',
          '--payload_size=512',
          '--key_range=100000',
          '--read_rate=$READ_RATE',
          '--n_threads=$N_THREADS',
          '--thinking_time=2',
          '--log_frequency=20',
          '--buffer_size=1024'
        ]
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
      restartPolicy: Never
      # nodeSelector:
      #   role: client
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: name
      #               operator: In
      #               values: [ "http-log-client" ]
      #         topologyKey: failure-domain.beta.kubernetes.io/zone
