apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-kv-hashicorp-raft-followers
  labels:
    app: tcp-kv-hashicorp-raft-followers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcp-kv-hashicorp-raft-followers
  template:
    metadata:
      labels:
        app: tcp-kv-hashicorp-raft-followers
    spec:
      containers:
        - name: tcp-kv-hashicorp-raft-followers
          image: r3musketeers/tcp-kv-hashicorp-raft
          args: [
            "-l", "/tmp/throughput.log",
            "-b", "1024",
            "-j", "tcp-kv-hashicorp-raft-leader:9000",
            "-v", "512"
          ]
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROTOCOL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PROTOCOL_PORT
              value: "10000"
          ports:
            - name: server
              containerPort: 8000
            - name: join
              containerPort: 9000
            - name: protocol
              containerPort: 10000
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          readinessProbe:
            tcpSocket:
              port: 8000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - hardworker
                  - key: name
                    operator: In
                    values: [ "tcp-kv-hashicorp-raft-leader", "tcp-kv-hashicorp-raft-followers" ]
