name: CI

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cancel:
    name: auto-cancellation-running-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fauguste/auto-cancellation-running-action@0.1.4
        with:
          githubToken: ${{ secrets.CANCEL_WORKFLOW_KEY }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker pull lptonussi/hermes
      - run: docker pull lptonussi/http-log-client
      - run: docker pull lptonussi/http-log-server
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

  testing:
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 25
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     ci_node_total: [4]
    #     ci_node_index: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t local/example .
          echo -n "verifying images:"
          docker images        
      - name: Deploy to minikube
        run:
          kubectl apply -f deploy-to-minikube.yaml
      - name: Test service URLs
        run: |
          minikube service list
          minikube service example --url
          echo "------------------opening the service------------------"
          curl $(minikube service example --url)    

      - name: Label
        run: |
          kubectl get nodes
          kubectl label nodes k3d-hermes-agent-0 role=server --overwrite
          kubectl label nodes k3d-hermes-agent-1 role=server --overwrite
          kubectl label nodes k3d-hermes-agent-2 role=client --overwrite
          kubectl label nodes k3d-hermes-agent-0 kubernetes.io/role=server --overwrite
          kubectl label nodes k3d-hermes-agent-1 kubernetes.io/role=server --overwrite
          kubectl label nodes k3d-hermes-agent-2 kubernetes.io/role=client --overwrite

      - name: "Docker repo demo"
        shell: bash
        run: |
          ./scripts/experiment.sh kubernetes 1 $(expr 2 \/ 1) 50 e3/1000-rw

      - name: Tar experiments
        run: tar -cvf 1000-rw.tar e3/1000-rw

      - name: Save experiments
        uses: actions/upload-artifact@v3
        with:
          name: 1000-rw
          path: 1000-rw.tar
